spring:
  application:
    name: demo-service-consumer

server:
  port: 8050

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/ #eureka服务注册地址

feign:
  feign:
    compression:
      request:
        enabled: true
        min-request-size: 2048
        mime-types:
        - text/xml
        - application/xml
        - application/json
      response:
        enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic

#actuator端口
management:
  server:
    port: 8051
  endpoints:
    health:
      show-details: always
    web:
      #   base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点